# Generated by Django 5.0.2 on 2024-02-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='products',
            name='numbers',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество продуктов'),
        ),
    ]
