# Generated by Django 5.0.2 on 2024-02-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_orders_options_products_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='back_to_main',
            field=models.BooleanField(default=False, verbose_name='На главную'),
        ),
        migrations.AddField(
            model_name='products',
            name='date_add',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
