# Generated by Django 5.0.2 on 2024-02-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_products_back_to_main_products_date_add'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Liked_Product',
            new_name='Wishlist',
        ),
    ]
