# Generated by Django 5.0.2 on 2024-03-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_liked_product_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.PositiveIntegerField(default=5, verbose_name='Оценка от 1 до 5'),
        ),
    ]
