# Generated by Django 5.0.2 on 2024-03-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_wishlist_options_alter_comments_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
        migrations.AddField(
            model_name='orders',
            name='fulfillment_status',
            field=models.CharField(choices=[('Не собран', 'Не собран'), ('Собран', 'Собран')], default='Не собран', max_length=50, verbose_name='Статус готовности'),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('Не оплачено', 'Не оплачено'), ('Оплачено', 'Оплачено')], default='Не оплачено', max_length=50, verbose_name='Статус оплаты'),
        ),
    ]
