# Generated by Django 5.0.2 on 2024-03-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_orders_status_orders_fulfillment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='mailing_list',
        ),
    ]
